stages:
  ingest_data:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/test.csv
    - data/train.csv
  preprocess_data:
    cmd: python3 src/data_preprocessing.py
    deps:
    - data/test.csv
    - data/train.csv
    - src/data_preprocessing.py
    outs:
    - data/processed/test_clean.csv
    - data/processed/train_clean.csv
  train_model:
    cmd: python3 src/train_model.py
    deps:
    - data/processed/test_clean.csv
    - data/processed/train_clean.csv
    - src/train_model.py
    outs:
    - models/report.txt
    - models/svm_pipeline.joblib
  evaluate_model:
    cmd: python3 src/evaluate_model.py
    deps:
    - data/processed/test_clean.csv
    - models/svm_pipeline.joblib
    - src/evaluate_model.py
    outs:
    - evaluation/confusion_matrix.png
  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
    - data/processed/test_clean.csv
    - data/processed/train_clean.csv
    - src/feature_engineering.py
    outs:
    - data/processed/test_bow.csv
    - data/processed/train_bow.csv
    - models/vectorizer.joblib
  train_bert:
    cmd: python3 src/train_bert.py
    deps:
    - data/processed/train_clean.csv
    - src/train_bert.py
    outs:
    - models/bert
  evaluate_bert:
    cmd: python3 src/evaluate_bert.py
    deps:
    - data/processed/test_clean.csv
    - models/bert
    - src/evaluate_bert.py
    outs:
    - evaluation/bert_confusion_matrix.png
    - evaluation/bert_report.txt
